spring:
  ai:
    dashscope:
      api-key: sk-5ac8c8939f9c40df853da24ba16b55a1
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-index

  data:
    redis:
      host: 47.98.113.40
      port: 6379
      username: default
      password: